[project]
name = "stacksnation-c"
authors = ["abrahamekio"]
description = "Stacksnation is a token marketplace built to support creators in Africa and bring more innovation to bitcoin  nfts in the stacks ecosystem."
telemetry = true
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[project.cache_location]
path = ".requirements"
[contracts.sip-trait]
path = "contracts/sip-trait.clar"

[contracts.sip009]
path = "contracts/sip009.clar"

[contracts.stacksnation-c]
path = "contracts/stacksnation-c.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
